version: '3.7'
services:
  blog:
    image: registry.cn-chengdu.aliyuncs.com/lyx_blog/shiyi-blog
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/shiyi_blog?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&tinyInt1isBit=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_REDIS_HOST: redis
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8989:80"
    networks:
      - db_db

networks:
  db_db:
    external: true