name: 构建并推送到阿里云容器注册表

# 触发条件：推送到main分支或创建标签时触发
on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检查代码
        uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: 使用 Maven 构建
        run: |
          cd blog
          mvn -B package --file pom.xml

      - name: 提取项目版本
        id: extract-version
        run: |
          echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT

      - name: 登录阿里云容器注册表
        uses: aliyun/acr-login@v1
        with:
          login-server: ${{ secrets.ALIYUN_ACR_REGISTRY }}  # 例如：registry.cn-beijing.aliyuncs.com
          username: ${{ secrets.ALIYUN_ACR_USERNAME }}
          password: ${{ secrets.ALIYUN_ACR_PASSWORD }}

      - name: 构建和推送 Docker 镜像
        env:
          ACR_REGISTRY: ${{ secrets.ALIYUN_ACR_REGISTRY }}
          ACR_NAMESPACE: ${{ secrets.ALIYUN_ACR_NAMESPACE }}  # 你的命名空间
          IMAGE_NAME: shiyi-blog  # 镜像名称
        run: |
          # 构建镜像
          docker build -t $ACR_REGISTRY/$ACR_NAMESPACE/$IMAGE_NAME:${{ steps.extract-version.outputs.VERSION }} .
          
          # 如果是标签推送，额外添加latest标签
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            docker tag $ACR_REGISTRY/$ACR_NAMESPACE/$IMAGE_NAME:${{ steps.extract-version.outputs.VERSION }} $ACR_REGISTRY/$ACR_NAMESPACE/$IMAGE_NAME:latest
            docker push $ACR_REGISTRY/$ACR_NAMESPACE/$IMAGE_NAME:latest
          fi
          
          # 推送版本标签镜像
          docker push $ACR_REGISTRY/$ACR_NAMESPACE/$IMAGE_NAME:${{ steps.extract-version.outputs.VERSION }}